bind_addr = ":8099"
log_level = "debug"
database_url = "host=192.168.253.229 dbname=wstbd user=postgres password=postgres sslmode=disable "
session_key = "NzaC1yc2EAAAADAQABAAABAQDJDcVuPZnkgqBcnGuBWEIw9Xo+a/ZLMbLscHgsuiw9riRId1tr3+4dIBB3NIL2IeD3/ZJJ3kuVbNYRzKGLAt8oMnQnm5iJDkFVXcZDWaslu4wZB+kcZQX9EOvTjciMc74tb9HHmmAIYfqawpoNZK2rqUJmkzvPJ/tjMGJDvdN87ujc7/7orCOmpvKxehBxz7ylec+FSrEkZZDE"